services:
  postgres:
    image: postgres:14-alpine
    restart: always
    environment: 
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data

  api:
    container_name: servindo_cms_api
    restart: always
    image: servindo-cms-be/nodejs
    command: sh -c './wait-for-it.sh postgres:5432 -- npm run sequelize:db:seed ; node src/index.js'
    ports:
      - 8000:8000
    depends_on:
      - postgres
    environment:
      - PORT=${API_PORT}
      - NODE_ENV=${API_NODE_ENV}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DIALECT=${DB_DIALECT}
      - CORS_ORIGIN=${CORS_ORIGIN}

volumes:
  postgres: